const test=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
class Range{constructor(sheet,r,c,nr,nc){Object.assign(this,{sheet,r,c,nr,nc})}getValues(){return Array.from({length:this.nr},(_,i)=>Array.from({length:this.nc},(_,j)=>this.sheet.data[this.r-1+i]?.[this.c-1+j]??''))}setValues(v){v.forEach((row,i)=>row.forEach((x,j)=>{this.sheet.data[this.r-1+i]??=[];this.sheet.data[this.r-1+i][this.c-1+j]=x}));return this}setValue(v){return this.setValues([[v]])}}
class Sheet{constructor(){this.data=[]}getLastRow(){return this.data.length}getRange(r,c,nr=1,nc=1){return new Range(this,r,c,nr,nc)}appendRow(r){this.data.push(r.slice())}setFrozenRows(){}}
function harness(){const sheets={},users=[
 {username:'creator',display_name:'المنشئ',status:'active',allowed_pages:'tasks',access_level:'workstream'},
 {username:'recipient',display_name:'المستلم',status:'active',allowed_pages:'tasks',access_level:'workstream'},
 {username:'outsider',display_name:'غير مخول',status:'active',allowed_pages:'overview',access_level:'workstream'},
 {username:'admin',display_name:'الإدارة',status:'active',allowed_pages:'*',access_level:'full',can_manage_users:'TRUE'}];
 const ss={getSheetByName:n=>sheets[n]||null,insertSheet:n=>sheets[n]=new Sheet()};let seq=0;
 const context={console,Date,RegExp,String,Object,Array,Error,Math,JSON,KAG_CONFIG:{inquiriesSheetName:'Inquiries',inquiryRepliesSheetName:'Replies',inquiryEventsSheetName:'Events',inquiryReadsSheetName:'Reads',inquiryNotificationsSheetName:'Notifications',usersSheetName:'Users'},SPREADSHEET_ID:'test',SpreadsheetApp:{openById:()=>ss},Utilities:{getUuid:()=>`uuid-${++seq}`},LockService:{getScriptLock:()=>({waitLock(){},hasLock(){return true},releaseLock(){}})},getRegisterRows_:()=>users,getUserAccessHeaders_:()=>[],hasFullAccess_:u=>u.access_level==='full',parseBool_:v=>v===true||v==='TRUE',normalizeAllowedPages_:u=>String(u.allowed_pages||'').split(','),readOfficialWbsTasks_:()=>({rows:[{code:'T-1',name:'مهمة مسموحة',owner:'المستلم',ownerEmail:''}]}),taskCode_:t=>t.code,taskName_:t=>t.name,taskOwner_:t=>t.owner,taskField_:(t,k)=>k==='ownerEmail'?t.ownerEmail:''};
 vm.createContext(context);vm.runInContext(fs.readFileSync('apps-script/Inquiries.gs','utf8'),context);return {c:context,users,sheets};}
function call(c,action,user,p={}){return c.handleInquiryAction_(Object.assign({action},p),user)}
test('دورة الاستفسار تحفظ وتطبق الصلاحيات والحالات والتنبيهات وعدم التكرار',()=>{const {c,users,sheets}=harness(),[creator,recipient,outsider,admin]=users;c.ensureInquirySheets_();
 const made=call(c,'inquiry_create',creator,{request_id:'create-1',title:'  سؤال فعلي  ',details:'تفاصيل',recipient_username:'recipient',priority:'عاجل'});const id=made.inquiry.inquiry_id;assert.equal(made.inquiry.title,'سؤال فعلي');assert.equal(call(c,'inquiry_create',creator,{request_id:'create-1',title:'سؤال فعلي',details:'تفاصيل',recipient_username:'recipient'}).deduplicated,true);assert.equal(sheets.Inquiries.getLastRow(),2);assert.throws(()=>call(c,'inquiry_detail',outsider,{inquiry_id:id}),/Forbidden/);assert.equal(call(c,'inquiry_list',recipient,{scope:'assigned'}).items.length,1);
 call(c,'inquiry_status',recipient,{inquiry_id:id,status:'قيد المعالجة',request_id:'status-1'});assert.throws(()=>call(c,'inquiry_status',recipient,{inquiry_id:id,status:'مغلق',request_id:'bad-close'}),/غير مسموح/);
 call(c,'inquiry_answer',recipient,{inquiry_id:id,body:'الإجابة',request_id:'reply-1'});assert.equal(call(c,'inquiry_reply',recipient,{inquiry_id:id,body:'الإجابة',request_id:'reply-1'}).deduplicated,true);assert.equal(call(c,'inquiry_detail',creator,{inquiry_id:id}).inquiry.status,'تمت الإجابة');call(c,'inquiry_reply',creator,{inquiry_id:id,body:'متابعة',request_id:'reply-2'});assert.equal(call(c,'inquiry_detail',creator,{inquiry_id:id}).inquiry.status,'قيد المعالجة');call(c,'inquiry_status',creator,{inquiry_id:id,status:'مغلق',request_id:'close-1'});assert.throws(()=>call(c,'inquiry_reply',recipient,{inquiry_id:id,body:'ممنوع',request_id:'reply-3'}),/أعد فتح/);call(c,'inquiry_status',creator,{inquiry_id:id,status:'قيد المعالجة',request_id:'reopen-1'});call(c,'inquiry_redirect',admin,{inquiry_id:id,recipient_username:'admin',request_id:'redirect-1'});assert.equal(call(c,'inquiry_redirect',admin,{inquiry_id:id,recipient_username:'admin',request_id:'redirect-1'}).deduplicated,true);assert.throws(()=>call(c,'inquiry_detail',recipient,{inquiry_id:id}),/Forbidden/);assert.equal(call(c,'inquiry_detail',admin,{inquiry_id:id}).inquiry.status,'جديد');assert.ok(sheets.Notifications.getLastRow()>1);
});
test('يرفض مستلما لا يرى المهمة ويطابق عدادات الملخص مع القائمة',()=>{const {c,users}=harness(),[creator,recipient,outsider]=users;c.ensureInquirySheets_();assert.throws(()=>call(c,'inquiry_create',creator,{request_id:'x',title:'مرتبط',details:'تفاصيل',recipient_username:'outsider',task_id:'T-1'}),/المستلم/);call(c,'inquiry_create',creator,{request_id:'ok',title:'مرتبط',details:'تفاصيل',recipient_username:'recipient',task_id:'T-1'});const list=call(c,'inquiry_list',recipient,{scope:'assigned'});assert.equal(list.summary.needs_reply,list.items.filter(x=>['جديد','قيد المعالجة'].includes(x.status)).length);});
