/* مركز الاستفسارات. انسخ هذا الملف و Code.gs إلى مشروع Apps Script نفسه. */
const INQUIRY_PROJECT_ID = 'KAG';
const INQUIRY_STATUS = ['جديد','قيد المعالجة','تمت الإجابة','مغلق'];
const INQUIRY_PRIORITY = ['عادي','عاجل'];

function inquiryHeaders_(){return ['inquiry_id','project_id','title','details','sender_username','recipient_username','task_id','task_title','priority','status','created_at','updated_at','request_id'];}
function inquiryReplyHeaders_(){return ['reply_id','inquiry_id','project_id','author_username','body','created_at','request_id'];}
function inquiryEventHeaders_(){return ['event_id','inquiry_id','project_id','event_type','actor_username','from_value','to_value','created_at','request_id'];}
function inquiryReadHeaders_(){return ['inquiry_id','project_id','username','last_read_at'];}
function inquiryNotificationHeaders_(){return ['notification_id','project_id','inquiry_id','username','kind','created_at','read_at','request_key'];}
function inquirySheet_(name,headers){const ss=SpreadsheetApp.openById(SPREADSHEET_ID);let s=ss.getSheetByName(name);if(!s){s=ss.insertSheet(name);s.getRange(1,1,1,headers.length).setValues([headers]);s.setFrozenRows(1);}return s;}
function inquiryRows_(name,headers){const s=inquirySheet_(name,headers), n=s.getLastRow();if(n<2)return [];return s.getRange(2,1,n-1,headers.length).getValues().map(function(v,i){const o={_row:i+2};headers.forEach(function(h,j){o[h]=v[j] instanceof Date?v[j].toISOString():String(v[j]===undefined?'':v[j]);});return o;});}
function inquiryAppend_(name,headers,obj){inquirySheet_(name,headers).appendRow(headers.map(function(h){return obj[h]===undefined?'':obj[h];}));return obj;}
function inquiryNow_(){return new Date().toISOString();}
function inquiryText_(v,max,label){const s=String(v===undefined?'':v).trim();if(!s)throw new Error(label+' مطلوب');if(s.length>max)throw new Error(label+' يتجاوز الحد المسموح');return s;}
function inquiryIsAdmin_(u){return hasFullAccess_(u)||parseBool_(u.can_manage_users);}
function inquiryCanUse_(u){return !!u&&!!u.username;}
function inquiryCanViewTask_(u){const p=normalizeAllowedPages_(u);return hasFullAccess_(u)||p.indexOf('*')!==-1||p.indexOf('tasks')!==-1;}
function inquiryUsers_(){return getRegisterRows_(KAG_CONFIG.usersSheetName,getUserAccessHeaders_()).filter(function(u){return String(u.status||'active').toLowerCase()==='active';});}
function inquiryPublicUser_(u){return {username:String(u.username||''),display_name:String(u.display_name||u.username||''),role:String(u.role||'')};}
function inquiryFindUser_(username){const key=String(username||'').trim().toLowerCase();return inquiryUsers_().find(function(u){return String(u.username||'').trim().toLowerCase()===key;})||null;}
function inquiryTask_(taskId){if(!taskId)return null;const rows=readOfficialWbsTasks_(SpreadsheetApp.openById(SPREADSHEET_ID)).rows;return rows.find(function(r){return taskCode_(r)===String(taskId);})||null;}
function inquiryEligibleRecipient_(username,task){const u=inquiryFindUser_(username);if(!u)throw new Error('المستلم غير نشط أو غير موجود');if(task&&!inquiryCanViewTask_(u))throw new Error('المستلم لا يملك صلاحية الاطلاع على المهمة');return u;}
function inquiryFind_(id){return inquiryRows_(KAG_CONFIG.inquiriesSheetName,inquiryHeaders_()).find(function(x){return x.inquiry_id===String(id)&&x.project_id===INQUIRY_PROJECT_ID;})||null;}
function inquiryCanAccess_(q,u){return inquiryIsAdmin_(u)||q.sender_username===u.username||q.recipient_username===u.username;}
function inquiryRequire_(id,u){const q=inquiryFind_(id);if(!q)throw new Error('الاستفسار غير موجود');if(!inquiryCanAccess_(q,u))throw new Error('Forbidden: inquiry access denied');return q;}
function inquiryDisplayNameMap_(){const m={};inquiryUsers_().forEach(function(u){m[u.username]=u.display_name||u.username;});return m;}
function inquiryUpdateRow_(q,changes){const h=inquiryHeaders_(),s=inquirySheet_(KAG_CONFIG.inquiriesSheetName,h);Object.keys(changes).forEach(function(k){q[k]=changes[k];});s.getRange(q._row,1,1,h.length).setValues([h.map(function(k){return q[k]||'';})]);return q;}
function inquiryEvent_(q,type,actor,from,to,requestId){return inquiryAppend_(KAG_CONFIG.inquiryEventsSheetName,inquiryEventHeaders_(),{event_id:Utilities.getUuid(),inquiry_id:q.inquiry_id,project_id:INQUIRY_PROJECT_ID,event_type:type,actor_username:actor.username,from_value:from||'',to_value:to||'',created_at:inquiryNow_(),request_id:requestId||''});}
function inquiryNotify_(q,username,kind,key){if(!username)return;const h=inquiryNotificationHeaders_(), rows=inquiryRows_(KAG_CONFIG.inquiryNotificationsSheetName,h);if(rows.some(function(n){return n.request_key===key&&n.username===username;}))return;inquiryAppend_(KAG_CONFIG.inquiryNotificationsSheetName,h,{notification_id:Utilities.getUuid(),project_id:INQUIRY_PROJECT_ID,inquiry_id:q.inquiry_id,username:username,kind:kind,created_at:inquiryNow_(),read_at:'',request_key:key});}
function inquiryMarkRead_(q,u){const h=inquiryReadHeaders_(),s=inquirySheet_(KAG_CONFIG.inquiryReadsSheetName,h),rows=inquiryRows_(KAG_CONFIG.inquiryReadsSheetName,h),r=rows.find(function(x){return x.inquiry_id===q.inquiry_id&&x.username===u.username;});const now=inquiryNow_(),vals={inquiry_id:q.inquiry_id,project_id:INQUIRY_PROJECT_ID,username:u.username,last_read_at:now};if(r)s.getRange(r._row,1,1,h.length).setValues([h.map(function(k){return vals[k];})]);else inquiryAppend_(KAG_CONFIG.inquiryReadsSheetName,h,vals);const nh=inquiryNotificationHeaders_(),ns=inquirySheet_(KAG_CONFIG.inquiryNotificationsSheetName,nh);inquiryRows_(KAG_CONFIG.inquiryNotificationsSheetName,nh).filter(function(n){return n.inquiry_id===q.inquiry_id&&n.username===u.username&&!n.read_at;}).forEach(function(n){ns.getRange(n._row,nh.indexOf('read_at')+1).setValue(now);});}
function inquirySerialize_(q,u,detail){const names=inquiryDisplayNameMap_(), reads=inquiryRows_(KAG_CONFIG.inquiryReadsSheetName,inquiryReadHeaders_()),read=reads.find(function(r){return r.inquiry_id===q.inquiry_id&&r.username===u.username;}),replies=inquiryRows_(KAG_CONFIG.inquiryRepliesSheetName,inquiryReplyHeaders_()).filter(function(r){return r.inquiry_id===q.inquiry_id;}).sort(function(a,b){return a.created_at.localeCompare(b.created_at);}),events=inquiryRows_(KAG_CONFIG.inquiryEventsSheetName,inquiryEventHeaders_()).filter(function(e){return e.inquiry_id===q.inquiry_id;}).sort(function(a,b){return a.created_at.localeCompare(b.created_at);}),hasUnreadNotification=inquiryRows_(KAG_CONFIG.inquiryNotificationsSheetName,inquiryNotificationHeaders_()).some(function(n){return n.inquiry_id===q.inquiry_id&&n.username===u.username&&!n.read_at;});const last=read?read.last_read_at:'';const out=Object.assign({},q,{sender_name:names[q.sender_username]||q.sender_username,recipient_name:names[q.recipient_username]||q.recipient_username,unread:hasUnreadNotification||replies.some(function(r){return r.author_username!==u.username&&(!last||r.created_at>last);})});if(q.task_id&&!inquiryCanViewTask_(u)){out.task_id='';out.task_title='';}delete out._row;if(detail){out.replies=replies.map(function(r){return Object.assign({},r,{author_name:names[r.author_username]||r.author_username});});out.events=events.map(function(e){return Object.assign({},e,{actor_name:names[e.actor_username]||e.actor_username});});out.can_admin=inquiryIsAdmin_(u);out.can_reply=q.status!=='مغلق';}return out;}
function inquiryList_(u,scope){if(scope==='all'&&!inquiryIsAdmin_(u))throw new Error('Forbidden: administration required');return inquiryRows_(KAG_CONFIG.inquiriesSheetName,inquiryHeaders_()).filter(function(q){if(q.project_id!==INQUIRY_PROJECT_ID||!inquiryCanAccess_(q,u))return false;if(scope==='mine')return q.sender_username===u.username;if(scope==='assigned')return q.recipient_username===u.username;return true;}).map(function(q){return inquirySerialize_(q,u,false);}).sort(function(a,b){return b.updated_at.localeCompare(a.updated_at);});}
function inquirySummary_(u){const all=inquiryList_(u,'visible'),reads=inquiryRows_(KAG_CONFIG.inquiryReadsSheetName,inquiryReadHeaders_()),replies=inquiryRows_(KAG_CONFIG.inquiryRepliesSheetName,inquiryReplyHeaders_());return {needs_reply:all.filter(function(q){return q.recipient_username===u.username&&(q.status==='جديد'||q.status==='قيد المعالجة');}).length,new_replies:all.filter(function(q){if(q.sender_username!==u.username)return false;const read=reads.find(function(r){return r.inquiry_id===q.inquiry_id&&r.username===u.username;}),last=read?read.last_read_at:'';return replies.some(function(r){return r.inquiry_id===q.inquiry_id&&r.author_username!==u.username&&(!last||r.created_at>last);});}).length};}
function inquiryBootstrap_(u){const active=inquiryUsers_(),users=active.filter(function(x){return x.username!==u.username;}).map(inquiryPublicUser_),tasks=inquiryCanViewTask_(u)?readOfficialWbsTasks_(SpreadsheetApp.openById(SPREADSHEET_ID)).rows.map(function(t){const eligible=active.filter(inquiryCanViewTask_),owner=String(taskOwner_(t)||''),email=String(taskField_(t,'ownerEmail')||'').trim().toLowerCase(),matches=eligible.filter(function(x){return (email&&String(x.email||'').trim().toLowerCase()===email)||String(x.display_name||'').trim()===owner;});return {id:taskCode_(t),title:taskName_(t),eligible_recipients:eligible.map(function(x){return x.username;}),suggested_recipient:matches.length===1?matches[0].username:''};}).filter(function(t){return t.id;}):[];return {ok:true,users:users,tasks:tasks,can_admin:inquiryIsAdmin_(u),summary:inquirySummary_(u),notifications:inquiryRows_(KAG_CONFIG.inquiryNotificationsSheetName,inquiryNotificationHeaders_()).filter(function(n){return n.username===u.username&&!n.read_at;}).filter(function(n){const q=inquiryFind_(n.inquiry_id);return q&&inquiryCanAccess_(q,u);})};}
function inquiryCreate_(p,u){const requestId=inquiryText_(p.request_id,100,'معرف الطلب'),existing=inquiryRows_(KAG_CONFIG.inquiriesSheetName,inquiryHeaders_()).find(function(q){return q.sender_username===u.username&&q.request_id===requestId;});if(existing)return {ok:true,inquiry:inquirySerialize_(existing,u,true),deduplicated:true};const title=inquiryText_(p.title,150,'العنوان'),details=inquiryText_(p.details,5000,'التفاصيل'),priority=String(p.priority||'عادي');if(INQUIRY_PRIORITY.indexOf(priority)<0)throw new Error('أولوية غير صالحة');const task=inquiryTask_(String(p.task_id||'').trim());if(p.task_id&&!task)throw new Error('المهمة غير موجودة');if(task&&!inquiryCanViewTask_(u))throw new Error('لا تملك صلاحية الاطلاع على المهمة');const recipient=inquiryEligibleRecipient_(p.recipient_username,task),now=inquiryNow_(),q={inquiry_id:Utilities.getUuid(),project_id:INQUIRY_PROJECT_ID,title:title,details:details,sender_username:u.username,recipient_username:recipient.username,task_id:task?taskCode_(task):'',task_title:task?taskName_(task):'',priority:priority,status:'جديد',created_at:now,updated_at:now,request_id:requestId};inquiryAppend_(KAG_CONFIG.inquiriesSheetName,inquiryHeaders_(),q);inquiryEvent_(q,'إنشاء',u,'','جديد',requestId);inquiryNotify_(q,recipient.username,'استفسار جديد','create:'+q.inquiry_id);return {ok:true,inquiry:inquirySerialize_(q,u,true)};}
function inquiryReply_(p,u,answer){const q=inquiryRequire_(p.inquiry_id,u);if(q.status==='مغلق')throw new Error('أعد فتح الاستفسار قبل الرد');const body=inquiryText_(p.body,5000,'الرد'),requestId=inquiryText_(p.request_id,100,'معرف الطلب'),all=inquiryRows_(KAG_CONFIG.inquiryRepliesSheetName,inquiryReplyHeaders_()),old=all.find(function(r){return r.author_username===u.username&&r.request_id===requestId;});if(old)return {ok:true,inquiry:inquirySerialize_(q,u,true),deduplicated:true};if(answer&&!(q.recipient_username===u.username||inquiryIsAdmin_(u)))throw new Error('Forbidden: current recipient required');const now=inquiryNow_();inquiryAppend_(KAG_CONFIG.inquiryRepliesSheetName,inquiryReplyHeaders_(),{reply_id:Utilities.getUuid(),inquiry_id:q.inquiry_id,project_id:INQUIRY_PROJECT_ID,author_username:u.username,body:body,created_at:now,request_id:requestId});let status=q.status;if(answer)status='تمت الإجابة';else if(u.username===q.sender_username&&q.status==='تمت الإجابة')status='قيد المعالجة';inquiryUpdateRow_(q,{status:status,updated_at:now});inquiryEvent_(q,'رد',u,'',status,requestId);const other=u.username===q.sender_username?q.recipient_username:q.sender_username;inquiryNotify_(q,other,'رد جديد','reply:'+requestId);return {ok:true,inquiry:inquirySerialize_(q,u,true)};}
function inquiryStatus_(p,u){const q=inquiryRequire_(p.inquiry_id,u),to=String(p.status||''),from=q.status,req=inquiryText_(p.request_id,100,'معرف الطلب');if(inquiryRows_(KAG_CONFIG.inquiryEventsSheetName,inquiryEventHeaders_()).some(function(e){return e.actor_username===u.username&&e.request_id===req;}))return {ok:true,inquiry:inquirySerialize_(q,u,true),deduplicated:true};if(INQUIRY_STATUS.indexOf(to)<0)throw new Error('حالة غير صالحة');const admin=inquiryIsAdmin_(u),sender=q.sender_username===u.username,recipient=q.recipient_username===u.username;let ok=false;if(to==='قيد المعالجة')ok=(from==='جديد'&&(recipient||admin))||(from==='مغلق'&&(sender||admin));if(to==='مغلق')ok=from!=='مغلق'&&(sender||admin);if(!ok)throw new Error('انتقال الحالة غير مسموح');inquiryUpdateRow_(q,{status:to,updated_at:inquiryNow_()});inquiryEvent_(q,to==='مغلق'?'إغلاق':'إعادة فتح/بدء معالجة',u,from,to,req);[q.sender_username,q.recipient_username].filter(function(x,i,a){return x!==u.username&&a.indexOf(x)===i;}).forEach(function(x){inquiryNotify_(q,x,to,'status:'+req+':'+x);});return {ok:true,inquiry:inquirySerialize_(q,u,true)};}
function inquiryRedirect_(p,u){if(!inquiryIsAdmin_(u))throw new Error('Forbidden: administration required');const q=inquiryRequire_(p.inquiry_id,u),req=inquiryText_(p.request_id,100,'معرف الطلب');if(inquiryRows_(KAG_CONFIG.inquiryEventsSheetName,inquiryEventHeaders_()).some(function(e){return e.actor_username===u.username&&e.request_id===req;}))return {ok:true,inquiry:inquirySerialize_(q,u,true),deduplicated:true};if(q.status==='مغلق')throw new Error('أعد فتح الاستفسار قبل إعادة التوجيه');const task=q.task_id?inquiryTask_(q.task_id):null,next=inquiryEligibleRecipient_(p.recipient_username,task);if(next.username===q.recipient_username)throw new Error('المستلم الجديد مطابق للحالي');const from=q.recipient_username;inquiryUpdateRow_(q,{recipient_username:next.username,status:'جديد',updated_at:inquiryNow_()});inquiryEvent_(q,'إعادة توجيه',u,from,next.username,req);inquiryNotify_(q,next.username,'إعادة توجيه','redirect:'+req);return {ok:true,inquiry:inquirySerialize_(q,u,true)};}
function handleInquiryAction_(p,u){if(!inquiryCanUse_(u))throw new Error('Unauthorized');const lock=LockService.getScriptLock();if(/^inquiry_(create|reply|answer|status|redirect)$/.test(p.action)){lock.waitLock(20000);}try{if(p.action==='inquiry_bootstrap')return inquiryBootstrap_(u);if(p.action==='inquiry_list')return {ok:true,items:inquiryList_(u,String(p.scope||'mine')),summary:inquirySummary_(u)};if(p.action==='inquiry_detail'){const q=inquiryRequire_(p.inquiry_id,u);inquiryMarkRead_(q,u);return {ok:true,inquiry:inquirySerialize_(q,u,true),summary:inquirySummary_(u)};}if(p.action==='inquiry_create')return inquiryCreate_(p,u);if(p.action==='inquiry_reply'||p.action==='inquiry_answer')return inquiryReply_(p,u,p.action==='inquiry_answer');if(p.action==='inquiry_status')return inquiryStatus_(p,u);if(p.action==='inquiry_redirect')return inquiryRedirect_(p,u);throw new Error('Unsupported inquiry action');}finally{if(lock&&lock.hasLock())lock.releaseLock();}}

/* تشغيل يدوي مرة واحدة في بيئة الاختبار/النشر لإنشاء الجداول المستقلة فقط. */
function ensureInquirySheets_(){inquirySheet_(KAG_CONFIG.inquiriesSheetName,inquiryHeaders_());inquirySheet_(KAG_CONFIG.inquiryRepliesSheetName,inquiryReplyHeaders_());inquirySheet_(KAG_CONFIG.inquiryEventsSheetName,inquiryEventHeaders_());inquirySheet_(KAG_CONFIG.inquiryReadsSheetName,inquiryReadHeaders_());inquirySheet_(KAG_CONFIG.inquiryNotificationsSheetName,inquiryNotificationHeaders_());}
